language: java
jdk:
  - oraclejdk8
script:
  - echo -e "bot.token=xxx \r\ntransit.url=http://api.winnipegtransit.com/v2/ \r\ntransit.key=xxx \r\ngoogle.api.url=https://maps.googleapis.com/maps/api/geocode/json \r\ngoogle.api.key=xxx" >> config.properties
  - mvn test -B
